name: Tests
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-22.04
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Check Node version
        run: node -v
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
