name: Deploy to server
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Tests
    uses: dizi-izi-plan/dizi-izi-frontend/.github/workflows/check.yml@main

  docker:
    name: Docker
    needs: lint
    uses: dizi-izi-plan/dizi-izi-frontend/.github/workflows/docker.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

  server:
    name: Server
    needs: docker
    uses: dizi-izi-plan/dizi-izi-backend/.github/workflows/server_refresh.yml@main
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
