name: Docker image build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed
  workflow_run:
    workflows: [ "Check" ]
    types:
      - completed

jobs:
  docker_image:
    name: Create and push docker image
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            diziizi/dizi-izi-frontend:latest
            diziizi/dizi-izi-frontend:pull_${{ github.event.pull_request.number }}
