name: linting, building and deploying to Vercel
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write
  id-token: write
concurrency:
  group: "vercel"
  cancel-in-progress: true
jobs:
  build-and-ui-testing:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    environment:
      name: vercel
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Modules
        run: npm ci --force
      - name: Build Production Project
        run: npm run build
        if: always()
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        if: always()
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: your-vercel-project-id
          vercel_org_id: your-vercel-org-id

  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci --force
      - name: linting typescript
        run: npm run lint
        if: always()
